import sys; print('%s %s' % (sys.executable or sys.platform, sys.version))
import sys; print('%s %s' % (sys.executable or sys.platform, sys.version))
print(1+1)
print(np.random(0,1))
import numpy as np
print(np.random(0,1))
print(np.random.rand()(0,1))
print(np.random.rand(0,1))
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
